var districtByIso = {
    'RU-BEL': 'belgorod',
    'RU-BRY': 'bryansk',
    'RU-VLA': 'vladimir',
    'RU-VOR': 'voronesh',
    'RU-IVA': 'ivanovo',
    'RU-KLU': 'kaluga',
    'RU-KOS': 'kostroma',
    'RU-KRS': 'kursk',
    'RU-LIP': 'lipezk',
    'RU-MOS': 'moscwa',
    'RU-MOW': 'moscow',
    'RU-ORL': 'orel',
    'RU-RYA': 'ryazan',
    'RU-SMO': 'smolensk',
    'RU-TAM': 'tambov',
    'RU-TVE': 'tver',
    'RU-TUL': 'tula',
    'RU-YAR': 'yaroslavl',
    'RU-ARK': 'arhangel',
    'RU-VLG': 'vologda',
    'RU-KGD': 'kalinin',
    'RU-KR': 'karelia',
    'RU-KO': 'komi',
    'RU-LEN': 'lenin',
    'RU-MUR': 'murmansk',
    'RU-NEN': 'nenezk',
    'RU-NGR': 'novgorod',
    'RU-PSK': 'pskov',
    'RU-SPE': 'peter',
    'RU-AD': 'adygea',
    'RU-AST': 'astrahan',
    'RU-VGG': 'volga',
    'RU-KL': 'kalmyk',
    'RU-KDA': 'krasnodar',
    'RU-SEV': 'sevastopol',
    'RU-KRY': 'krym',
    'RU-ROS': 'rostov',
    'RU-DA': 'dagestan',
    'RU-IN': 'ingush',
    'RU-KB': 'kabardino',
    'RU-KC': 'cerkesk',
    'RU-SE': 'osetia',
    'RU-STA': 'stavropol',
    'RU-CE': 'cecnya',
    'RU-BA': 'bashkort',
    'RU-KIR': 'kirov',
    'RU-ME': 'marii',
    'RU-MO': 'mordovia',
    'RU-NIZ': 'nizniy',
    'RU-ORE': 'orenburg',
    'RU-PNZ': 'penza',
    'RU-PER': 'perm',
    'RU-SAM': 'samara',
    'RU-SAR': 'saratov',
    'RU-TA': 'tatarstan',
    'RU-UD': 'udmurtia',
    'RU-ULY': 'ulyanovsk',
    'RU-CU': 'cuvashia',
    'RU-KGN': 'kurgan',
    'RU-SVE': 'eburg',
    'RU-TYU': 'tyumen',
    'RU-KHM': 'ugra',
    'RU-CHE': 'chelyaba',
    'RU-YAN': 'yamal',
    'RU-ALT': 'altayk',
    'RU-AL': 'altayr',
    'RU-BU': 'buryatia',
    'RU-ZAB': 'zabaikal',
    'RU-IRK': 'irkutsk',
    'RU-KEM': 'kemerovo',
    'RU-KYA': 'krasnoyarsk',
    'RU-NVS': 'novosib',
    'RU-OMS': 'omsk',
    'RU-TOM': 'tomsk',
    'RU-TY': 'tyva',
    'RU-KK': 'hakasia',
    'RU-AMU': 'amur',
    'RU-YEV': 'yevrey',
    'RU-KAM': 'kamchatka',
    'RU-MAG': 'magadan',
    'RU-PRI': 'primorie',
    'RU-SA': 'saha',
    'RU-SAK': 'sahalin',
    'RU-KHA': 'habarovsk',
    'RU-CHU': 'chukotka'

    // 'RU-BEL': 'cfo',
    // 'RU-BRY': 'cfo',
    // 'RU-VLA': 'cfo',
    // 'RU-VOR': 'cfo',
    // 'RU-IVA': 'cfo',
    // 'RU-KLU': 'cfo',
    // 'RU-KOS': 'cfo',
    // 'RU-KRS': 'cfo',
    // 'RU-LIP': 'cfo',
    // 'RU-MOS': 'cfo',
    // 'RU-MOW': 'cfo',
    // 'RU-ORL': 'cfo',
    // 'RU-RYA': 'cfo',
    // 'RU-SMO': 'cfo',
    // 'RU-TAM': 'cfo',
    // 'RU-TVE': 'cfo',
    // 'RU-TUL': 'cfo',
    // 'RU-YAR': 'cfo',
    // 'RU-ARK': 'szfo',
    // 'RU-VLG': 'szfo',
    // 'RU-KGD': 'szfo',
    // 'RU-KR': 'szfo',
    // 'RU-KO': 'szfo',
    // 'RU-LEN': 'szfo',
    // 'RU-MUR': 'szfo',
    // 'RU-NEN': 'szfo',
    // 'RU-NGR': 'szfo',
    // 'RU-PSK': 'szfo',
    // 'RU-SPE': 'szfo',
    // 'RU-AD': 'yfo',
    // 'RU-AST': 'yfo',
    // 'RU-VGG': 'yfo',
    // 'RU-KL': 'yfo',
    // 'RU-KDA': 'yfo',
    // 'RU-SEV': 'yfo',
    // 'RU-KRY': 'yfo',
    // 'RU-ROS': 'yfo',
    // 'RU-DA': 'skfo',
    // 'RU-IN': 'skfo',
    // 'RU-KB': 'skfo',
    // 'RU-KC': 'skfo',
    // 'RU-SE': 'skfo',
    // 'RU-STA': 'skfo',
    // 'RU-CE': 'skfo',
    // 'RU-BA': 'pfo',
    // 'RU-KIR': 'pfo',
    // 'RU-ME': 'pfo',
    // 'RU-MO': 'pfo',
    // 'RU-NIZ': 'pfo',
    // 'RU-ORE': 'pfo',
    // 'RU-PNZ': 'pfo',
    // 'RU-PER': 'pfo',
    // 'RU-SAM': 'pfo',
    // 'RU-SAR': 'pfo',
    // 'RU-TA': 'pfo',
    // 'RU-UD': 'pfo',
    // 'RU-ULY': 'pfo',
    // 'RU-CU': 'pfo',
    // 'RU-KGN': 'urfo',
    // 'RU-SVE': 'urfo',
    // 'RU-TYU': 'urfo',
    // 'RU-KHM': 'urfo',
    // 'RU-CHE': 'urfo',
    // 'RU-YAN': 'urfo',
    // 'RU-ALT': 'sfo',
    // 'RU-AL': 'sfo',
    // 'RU-BU': 'sfo',
    // 'RU-ZAB': 'sfo',
    // 'RU-IRK': 'sfo',
    // 'RU-KEM': 'sfo',
    // 'RU-KYA': 'sfo',
    // 'RU-NVS': 'sfo',
    // 'RU-OMS': 'sfo',
    // 'RU-TOM': 'sfo',
    // 'RU-TY': 'sfo',
    // 'RU-KK': 'sfo',
    // 'RU-AMU': 'dfo',
    // 'RU-YEV': 'dfo',
    // 'RU-KAM': 'dfo',
    // 'RU-MAG': 'dfo',
    // 'RU-PRI': 'dfo',
    // 'RU-SA': 'dfo',
    // 'RU-SAK': 'dfo',
    // 'RU-KHA': 'dfo',
    // 'RU-CHU': 'dfo'
};
